### ISSUE TITLE
Add pkitools.net to the list

### ISSUE THREAD

**Issue by hg2214119** [yurt-page/Awesome-Cryptography-GUI#5]
I think this [website](https://pkitools.net/) is awesome too !

**Comment by gdmeunier** [comment]
Hello,
Thanks for sharing this website

I added it to the See Also list, alongwith the Awesome-Cryptography list & Cryptool.

I'm also really interested in being able to get the source code for that website.
I didn't find any way to get it even on the dev's Github repo.

If it was possible to have the source, then I would be able to use it as a controlled audit-friendly signing portal much like what paid online eSigner services do.

Thanks again for telling us about it!
